package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * AppAuth generated by hbm2java
 */
public class AppAuth implements java.io.Serializable {

	private Integer appAuthId;
	private String authName;
	private String authDescription;

	public AppAuth() {
	}

	public AppAuth(String authName, String authDescription) {
		this.authName = authName;
		this.authDescription = authDescription;
	}

	public Integer getAppAuthId() {
		return this.appAuthId;
	}

	public void setAppAuthId(Integer appAuthId) {
		this.appAuthId = appAuthId;
	}

	public String getAuthName() {
		return this.authName;
	}

	public void setAuthName(String authName) {
		this.authName = authName;
	}

	public String getAuthDescription() {
		return this.authDescription;
	}

	public void setAuthDescription(String authDescription) {
		this.authDescription = authDescription;
	}

}
