package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String customerName;
	private Integer noOfUserNominatedReviewers;
	private Integer noOfAdminNominatedReviewers;

	public Customer() {
	}

	public Customer(String customerName, Integer noOfUserNominatedReviewers,
			Integer noOfAdminNominatedReviewers) {
		this.customerName = customerName;
		this.noOfUserNominatedReviewers = noOfUserNominatedReviewers;
		this.noOfAdminNominatedReviewers = noOfAdminNominatedReviewers;
	}

	public Customer(int custId)
	{
		customerId = custId;
	}

	public Customer(Integer cId, String cName) {
		customerId = cId;
		customerName = cName;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public Integer getNoOfUserNominatedReviewers() {
		return this.noOfUserNominatedReviewers;
	}

	public void setNoOfUserNominatedReviewers(Integer noOfUserNominatedReviewers) {
		this.noOfUserNominatedReviewers = noOfUserNominatedReviewers;
	}

	public Integer getNoOfAdminNominatedReviewers() {
		return this.noOfAdminNominatedReviewers;
	}

	public void setNoOfAdminNominatedReviewers(
			Integer noOfAdminNominatedReviewers) {
		this.noOfAdminNominatedReviewers = noOfAdminNominatedReviewers;
	}

}
