package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * DesignationQuestion generated by hbm2java
 */
public class DesignationQuestion implements java.io.Serializable {

	private DesignationQuestionId id;
	
	private Integer m_questionId;
	private Integer m_designationId;

	public DesignationQuestion() {
	}

	public DesignationQuestion(DesignationQuestionId id) {
		this.id = id;
	}

	public DesignationQuestion(Integer questionId, Integer designationId) {
		m_questionId = questionId;
		m_designationId = designationId;
				
	}

	public DesignationQuestionId getId() {
		return this.id;
	}

	public void setId(DesignationQuestionId id) {
		this.id = id;
	}

	public Integer getQuestionId() {
		return m_questionId;
	}

	public void setQuestionId(Integer questionId) {
		m_questionId = questionId;
	}

	public Integer getDesignationId() {
		return m_designationId;
	}

	public void setDesignationId(Integer designationId) {
		m_designationId = designationId;
	}

}
