package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * DesignationQuestionId generated by hbm2java
 */
public class DesignationQuestionId implements java.io.Serializable {

	private int designationQuestionId;
	private int questionId;

	public DesignationQuestionId() {
	}

	public DesignationQuestionId(int designationQuestionId, int questionId) {
		this.designationQuestionId = designationQuestionId;
		this.questionId = questionId;
	}

	public int getDesignationQuestionId() {
		return this.designationQuestionId;
	}

	public void setDesignationQuestionId(int designationQuestionId) {
		this.designationQuestionId = designationQuestionId;
	}

	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DesignationQuestionId))
			return false;
		DesignationQuestionId castOther = (DesignationQuestionId) other;

		return (this.getDesignationQuestionId() == castOther
				.getDesignationQuestionId())
				&& (this.getQuestionId() == castOther.getQuestionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDesignationQuestionId();
		result = 37 * result + this.getQuestionId();
		return result;
	}

}
