package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * EmployeeFeedbackAnswer generated by hbm2java
 */
public class EmployeeFeedbackAnswer implements java.io.Serializable {

	private Integer appUserFeedbackAnswerId;
	private int appUserReviewerId;
	private int questionId;
	private String descriptiveAnswer;
	
	private Question m_question;
	private MultipleChoiceAnswer m_multipleChoiceAnswer;

	public EmployeeFeedbackAnswer() {
	}

	public EmployeeFeedbackAnswer(int appUserReviewerId, int questionId) {
		this.appUserReviewerId = appUserReviewerId;
		this.questionId = questionId;
	}

	public EmployeeFeedbackAnswer(int appUserReviewerId, int questionId,
			String descriptiveAnswer) {
		this.appUserReviewerId = appUserReviewerId;
		this.questionId = questionId;
		this.descriptiveAnswer = descriptiveAnswer;
	}

	public Integer getAppUserFeedbackAnswerId() {
		return this.appUserFeedbackAnswerId;
	}

	public void setAppUserFeedbackAnswerId(Integer appUserFeedbackAnswerId) {
		this.appUserFeedbackAnswerId = appUserFeedbackAnswerId;
	}

	public int getAppUserReviewerId() {
		return this.appUserReviewerId;
	}

	public void setAppUserReviewerId(int appUserReviewerId) {
		this.appUserReviewerId = appUserReviewerId;
	}

	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public String getDescriptiveAnswer() {
		return this.descriptiveAnswer;
	}

	public void setDescriptiveAnswer(String descriptiveAnswer) {
		this.descriptiveAnswer = descriptiveAnswer;
	}

	public Question getQuestion() {
		return m_question;
	}

	public void setQuestion(Question question) {
		m_question = question;
	}

	public MultipleChoiceAnswer getMultipleChoiceAnswer() {
		return m_multipleChoiceAnswer;
	}

	public void setMultipleChoiceAnswer(MultipleChoiceAnswer multipleChoiceAnswer) {
		m_multipleChoiceAnswer = multipleChoiceAnswer;
	}

}
