package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * MultipleChoiceAnswer generated by hbm2java
 */
public class MultipleChoiceAnswer implements java.io.Serializable {

	private Integer multipleChoiceAnswerId;
	private int appUserFeedbackAnswerAppUserFeedbackAnswerId;
	private int multipleChoiceId;
	
	private MultipleChoice m_multipleChoice;

	public MultipleChoiceAnswer() {
	}

	public MultipleChoiceAnswer(
			int appUserFeedbackAnswerAppUserFeedbackAnswerId,
			int multipleChoiceMultipleChoiceId) {
		this.appUserFeedbackAnswerAppUserFeedbackAnswerId = appUserFeedbackAnswerAppUserFeedbackAnswerId;
		this.multipleChoiceId = multipleChoiceMultipleChoiceId;
	}

	public Integer getMultipleChoiceAnswerId() {
		return this.multipleChoiceAnswerId;
	}

	public void setMultipleChoiceAnswerId(Integer multipleChoiceAnswerId) {
		this.multipleChoiceAnswerId = multipleChoiceAnswerId;
	}

	public int getAppUserFeedbackAnswerAppUserFeedbackAnswerId() {
		return this.appUserFeedbackAnswerAppUserFeedbackAnswerId;
	}

	public void setAppUserFeedbackAnswerAppUserFeedbackAnswerId(
			int appUserFeedbackAnswerAppUserFeedbackAnswerId) {
		this.appUserFeedbackAnswerAppUserFeedbackAnswerId = appUserFeedbackAnswerAppUserFeedbackAnswerId;
	}

	public int getMultipleChoiceId() {
		return multipleChoiceId;
	}

	public void setMultipleChoiceId(int multipleChoiceId) {
		this.multipleChoiceId = multipleChoiceId;
	}


}
