package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * MultipleChoice generated by hbm2java
 */
public class MultipleChoice implements java.io.Serializable {

	private Integer m_multipleChoiceId;
	private int m_questionId;
	private String m_answer;
	private Integer m_sequesnce;
	
	private RatingScale m_ratingScale ;
	
	private Question m_question;

	public MultipleChoice() {
	}

	public MultipleChoice(int questionId) {
		this.m_questionId = questionId;
	}

	public MultipleChoice(int questionId, String answer, Integer sequesnce) {
		this.m_questionId = questionId;
		this.m_answer = answer;
		this.m_sequesnce = sequesnce;
	}

	public MultipleChoice(String choice, RatingScale ratingScale , int sequence) 
	{
		m_answer = choice;
		m_sequesnce= sequence;
		m_ratingScale = ratingScale;
	}

	public MultipleChoice(Integer multipleChoiceAnswerId, Integer questionId,
			String mcAnswer, Integer sequence) {
		
		m_multipleChoiceId = multipleChoiceAnswerId;
		m_questionId = questionId;
		m_answer = mcAnswer;
		m_sequesnce = sequence;
		
	}

	public MultipleChoice(int multipleChoiceId, String answer)
	{
		m_questionId = multipleChoiceId;
		m_answer = answer;
	}

	public Integer getMultipleChoiceId() {
		return m_multipleChoiceId;
	}

	public void setMultipleChoiceId(Integer multipleChoiceId) {
		m_multipleChoiceId = multipleChoiceId;
	}

	public int getQuestionId() {
		return m_questionId;
	}

	public void setQuestionId(int questionId) {
		m_questionId = questionId;
	}

	public String getAnswer() {
		return m_answer;
	}

	public void setAnswer(String answer) {
		m_answer = answer;
	}

	public Integer getSequesnce() {
		return m_sequesnce;
	}

	public void setSequesnce(Integer sequesnce) {
		m_sequesnce = sequesnce;
	}

	public Question getQuestion() {
		return m_question;
	}

	public void setQuestion(Question question) {
		m_question = question;
	}

	public RatingScale getRatingScale() {
		return m_ratingScale;
	}

	public void setRatingScale(RatingScale ratingScale) {
		m_ratingScale = ratingScale;
	}


}
