package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * RatingScale generated by hbm2java
 */
public class RatingScale implements java.io.Serializable {

	private Integer m_ratingScaleId;
	private int m_customerId;
	private Integer m_ranking;
	private String m_name;
	private Customer m_customer;

	public RatingScale() {
	}

	public RatingScale(int customerId) {
		this.m_customerId = customerId;
	}

	public RatingScale(int customerId, Integer ranking, String name) {
		this.m_customerId = customerId;
		this.m_ranking = ranking;
		this.m_name = name;
	}

	public RatingScale(String name, Integer ranking, Customer customer) {
		m_name = name;
		m_ranking = ranking;
		m_customer = customer;
			
	}

	public RatingScale(String name) {
		m_name = name;
	}

	public Integer getRatingScaleId() {
		return m_ratingScaleId;
	}

	public void setRatingScaleId(Integer ratingScaleId) {
		m_ratingScaleId = ratingScaleId;
	}

	public int getCustomerId() {
		return m_customerId;
	}

	public void setCustomerId(int customerId) {
		m_customerId = customerId;
	}

	public Integer getRanking() {
		return m_ranking;
	}

	public void setRanking(Integer ranking) {
		m_ranking = ranking;
	}

	public String getName() {
		return m_name;
	}

	public void setName(String name) {
		m_name = name;
	}

	public Customer getCustomer() {
		return m_customer;
	}

	public void setCustomer(Customer customer) {
		m_customer = customer;
	}

}
