package com.assess.service.entity;

// Generated Jul 7, 2014 8:27:18 AM by Hibernate Tools 3.4.0.CR1

/**
 * RefQuestionType generated by hbm2java
 */
public class RefQuestionType implements java.io.Serializable {

	private Integer refQuestionTypeId;
	private String questionType;

	public RefQuestionType() {
	}

	public RefQuestionType(String questionType) {
		this.questionType = questionType;
	}

	public Integer getRefQuestionTypeId() {
		return this.refQuestionTypeId;
	}

	public void setRefQuestionTypeId(Integer refQuestionTypeId) {
		this.refQuestionTypeId = refQuestionTypeId;
	}

	public String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}

}
